version: "3.8"

services:
  frontend:
    image: ghcr.io/ligre-lod/query-interface/frontend:latest
    pull_policy: always
    # build: apps/frontend
    ports:
      - "8080:8000"
    configs:
      - source: config.toml
        target: /config.toml
      - source: runtime-config.json
        target: /public/query-interface/config.json
    environment:
      - SERVER_CONFIG_FILE=/config.toml
    restart: unless-stopped

configs:
  config.toml:
    content: |
      [general]
      host = "0.0.0.0"
      port = 8000
      log-level = "info"
  runtime-config.json:
    content: |
      {
        "lodviewUrl": "${LODVIEW_URL:-http://localhost:8082}",
        "sparqlEndpointUrl": "${SPARQL_ENDPOINT_URL:-http://localhost:8081/sparql}",
        "sparqlPortalUrl": "${SPARQL_PORTAL_URL:-http://localhost:8081}"
      }
